### ISSUE TITLE
Explicitly prevent two nodes from being started on the same host

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#325]
Two nodes should not be able to run at the same time on one host.  I tried this and it is possible but almost certainly doesn't work as expected.

I started the master node as follows:

`node service.js -c ./examples/config/processor-master.yaml`

with the following `processor-master.yaml`

```
terafoundation:
    environment: 'development'

    connectors:
        # ***********************
        # Elastic Search Configuration
        # ***********************
        elasticsearch:
            default:
                host:
                    - "127.0.0.1:9200"
            es1:
                host:
                    - "127.0.0.1:9200"
            es2:
                host:
                    - "127.0.0.1:9201"

teraslice:
    ops_directory: '/app/source/examples/ops/'

    master: true
    master_hostname: "127.0.0.1"
    name: "teracluster"
```

I started what I thought would be a _worker node_ with the following:

`node service.js -c ./examples/config/processor-worker.yaml`

with the following `processor-worker.yaml`

```
terafoundation:
    environment: 'development'

    connectors:
        # ***********************
        # Elastic Search Configuration
        # ***********************
        elasticsearch:
            default:
                host:
                    - "127.0.0.1:9200"
            es1:
                host:
                    - "127.0.0.1:9200"
            es2:
                host:
                    - "127.0.0.1:9201"

teraslice:
    ops_directory: '/app/source/examples/ops/'

    master: false
    master_hostname: "127.0.0.1"
    name: "teracluster"
```

In the long run we should probably make this possible, but doing so might not be trivial and there isn't much benefit at the moment.
