### ISSUE TITLE
S3 connector schema

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#3358]
- some parameters listed in the schema are incorrect, in particular `s3ForcePathStyle` and `s3BucketEndpoint`. We need a more clear way to list the correct params needed.

**Comment by godber** [comment]
Right now our configs contain the following settings

```
                endpoint:
                accessKeyId:
                secretAccessKey:
                forcePathStyle: true
                sslEnabled: true
                certLocation: 
```
