### ISSUE TITLE
Reduce Overall Test Time by targetting

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#4075]
Explore options for reducing the test runtimes by only running tests for relevant sub-packages.

**Comment by godber** [comment]
But changing to it might be a huge hassle.

**Comment by sotojn** [comment]
I've looked into a couple ideas and have a proposed solution. We should create a new sub command within scripts or just a script that can be ran before we trigger the the other tests. For example lets say we had a script that would somehow handle all the logic for what tests need to be ran and which ones don't. Our `test.yaml` ci file would look something like this:

```yaml
  determine-tests-based-off-commit:
    runs-on: ubuntu-latest
    needs: compute-node-version-vars
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'
      - name: Install and build packages
        run: yarn && yarn setup
      - name: Determine tests to run
        id: determine
        # The output of determine-tests would be a json object that looks like this:
          # {
          #   "unit": true,
          #   "e2e": true,
          #   "website": false
          # }
        run: |
          echo "Running determine-tests..."
          JSON=$(yarn determine-tests)

          LINUX_UNIT_TESTS=$(echo "$JSON" | jq -r '.unit')
          E2E=$(echo "$JSON" | jq -r '.e2e')
          WEBSITE=$(echo "$JSON" | jq -r '.webiste')

          echo "unit=$UNIT" >> $GITHUB_OUTPUT
          echo "e2e=$E2E" >> $GITHUB_OUTPUT
          echo "website=$WEBSITE" >> $GITHUB_OUTPUT

  linux-unit-tests:
    if: needs.determine-tests-based-off-commit.outputs.unit == 'true'
    runs-on: ubuntu-latest
    needs: [determine-tests-based-off-commit, compute-node-version-vars]
    ....


  e2e-k8s-tests:
    if: needs.determine-tests-based-off-commit.outputs.e2e == 'true'
    runs-on: ubuntu-latest
    needs: [compute-node-version-vars, verify-build, cache-docker-images, cache-asset-bundles, determine-tests-based-off-commit]
    ...

  e2e-k8s-v2-tests:
    if: needs.determine-tests-based-off-commit.outputs.e2e == 'true'
    runs-on: ubuntu-latest
    ....

  test-website:
    if: needs.determine-tests-based-off-commit.outputs.website == 'true'
    needs: [verify-build, determine-tests-based-off-commit]
```

As far as the logic of the script. It would:
- center around looking at whats changed in the latest commit
- determine what changes happened in what package
- find the dependency tree 
- Classify what tests should be ran, (for example any change that leads to a change in teraslice would trigger e2e tests. But if its just a change in the e2e directory, it will only run e2e tests.)

Maybe it could also see if the changed file is of a certain extension. Such as typescript, and see if the addition is only comment related. To not count that package as something that has been changed. Basically we would just be setting up path rules for all the packages, and when changed, would be marked for testing.

We could start off very broad by only focusing on a website change, which would only run website tests and expand furthur overtime.

This is better than adding something to `ts-scripts test` and determining it there because we would still be standing up all the runners even though we may only need a couple of them.
