### ISSUE TITLE
Multiple teraslice instances on one host

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#739]
When Teraslice `v0.36.5` has 1 master and 2 worker nodes on a single host, and a job is submitted requesting 1 worker and the assets exist, (see config below). I am seeing several issues in the logs, including the following:

- asset loader errors
- reducing worker count to 0
- port binding failures due to the port already existing
- multiple slicers being created, and failing (shouldn't there only be one?)
- WebSocket errors, for the slicers

## Teraslice Master

```yml
terafoundation:
    environment: 'development'
    log_level: info
    connectors:
        elasticsearch:
            default:
                host:
                    - "127.0.0.1:9200"
        kafka:
            default:
                brokers:
                    - "127.0.0.1:9092"

teraslice:
    master: true
    master_hostname: "127.0.0.1"
    workers: 4
    name: "teracluster"
```

## Teraslice Worker

```yml
terafoundation:
    environment: 'development'
    log_level: info
    connectors:
        elasticsearch:
            default:
                host:
                    - "127.0.0.1:9200"
        kafka:
            default:
                brokers:
                    - "127.0.0.1:9092"

teraslice:
    master: false
    master_hostname: "127.0.0.1"
    workers: 4
    name: "teracluster"
```

## Job

```json
{
    "name": "Data Generator",
    "lifecycle": "persistent",
    "workers": 1,
    "assets": [
        "random_processors"
    ],
    "operations": [
        {
            "_op": "elasticsearch_data_generator",
            "size": 10000
        },
        {
            "_op": "teraslice_kafka_sender",
            "topic": "testing-topic",
            "timestamp_field": "created",
            "id_field": "key"
        }
    ]
}
```
