### ISSUE TITLE
Add support for targeting jobs to specific nodes - affinity

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#794]
There are a few conditions where users may want to force pods to run on specific nodes or subsets of nodes.  For example:

* When a user has a k8s cluster that spans multiple zones, the user may want to force pods to run in a zone specified by a label
* To support targeting nodes with specific network permissions, these node can be specified by labels.

These constraints should be configurable at the job level.

**Comment by godber** [comment]
I propose we add a `cluster` property to the job that contains various job level directives that are related to the cluster manager.  In this particular case we would add `target` under `cluster` to specify details about targeting.

I think in the first implementation, lets just concern ourselves with **required** targets ... and ignore k8s support for preferred targets.

So for now, a job would look like:


```json
{
    "name": "gen-tenk-noop",
    "lifecycle": "persistent",
    "workers": 1,
    "cluster":{
        "target": [
            {"key": "zone", "value": "west"}
        ]},
    "operations": [
        {
            "_op": "elasticsearch_data_generator",
            "json_schema": "",
            "size": 10000,
            "start": "",
            "end": "",
            "format": "",
            "stress_test": false,
            "date_key": "created",
            "set_id": "",
            "id_start_key": ""
        },
        {
            "_op": "noop"
        }
    ],
    "analytics": true
}
```

which would result in the following addition to the jobs worker deployments:

```yaml
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - west
```

If we chose to implement preferred affinities, we can do this later.

```json
{
    "name": "gen-tenk-noop",
    "lifecycle": "persistent",
    "workers": 1,
    "cluster":{
        "target": [
            {"key": "zone", "value": "west"},
            {"key": "rack", "value": "r10", "required": false}
        ]},
    "operations": [
        {
            "_op": "elasticsearch_data_generator",
            "json_schema": "",
            "size": 10000,
            "start": "",
            "end": "",
            "format": "",
            "stress_test": false,
            "date_key": "created",
            "set_id": "",
            "id_start_key": ""
        },
        {
            "_op": "noop"
        }
    ],
    "analytics": true
}
```


```
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - west
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: rack
            operator: In
            values:
            - r10
```
