### ISSUE TITLE
Stuck Workers: Failure to update failed state

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#941]
There have been a number of times when teraslice jobs end up with stuck workers (workers with continuously increasing lag, never making progress).  These cases often show errors in the worker logs like this:

```
23:35:45.208Z  INFO worker: Resolving with 100000 results (module=operation, opName=teraslice_kafka_reader, jobName=myJob, jobId=7cd07716-0ab6-4a7a-8089-9818bb7c00bf, exId=a104af7d-d274-4952-abbd-d66892e35693)
23:37:53.850Z ERROR worker: (module=elasticsearch_backend)
    invoking elasticsearch-api _runRequest resulted in a runtime error: Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:354:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:383:7)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)
23:39:53.853Z ERROR worker: (module=elasticsearch_backend)
    invoking elasticsearch-api _runRequest resulted in a runtime error: Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:354:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:383:7)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)
23:39:53.854Z  INFO worker: analytics for slice: slice_id : 4c464058-5b5a-4ecc-9682-20c262f350b2 slicer_id : 0 slicer_order : 5372454 request : 1 _created : 2019-01-03T23:35:12.357Z time : 11659,967,15,2758,4892 memory : 39029928,105036920,3184784,100464152,9553160 size : 100000,100000,86738,133618,133618  (ex_id=a104af7d-d274-4952-abbd-d66892e35693, job_id=7cd07716-0ab6-4a7a-8089-9818bb7c00bf, module=slice, assignment=worker, slice_id=4c464058-5b5a-4ecc-9682-20c262f350b2)
23:39:53.854Z ERROR worker: (ex_id=a104af7d-d274-4952-abbd-d66892e35693, job_id=7cd07716-0ab6-4a7a-8089-9818bb7c00bf, module=worker, assignment=worker)
    slice run error for execution a104af7d-d274-4952-abbd-d66892e35693 Error: Failure to update failed state, caused by invoking elasticsearch-api _runRequest resulted in a runtime error: Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:354:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:383:7)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)
        at Slice._markFailed (/app/source/packages/teraslice/lib/workers/worker/slice.js:108:19)
        at <anonymous>
```

Note that the error has also been observed while updating success state:

```
16:56:12.831Z ERROR worker: (module=elasticsearch_backend)
    invoking elasticsearch-api _runRequest resulted in a runtime error: Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:354:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:383:7)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)
16:56:12.895Z ERROR worker: slice state for dd4acbc6-7698-42ba-bf79-3607e7583e54 has been marked as error (ex_id=dd4acbc6-7698-42ba-bf79-3607e7583e54, job_id=d3bdd26e-ba26-4e2f-a073-df67b7dc488c, module=slice, assignment=worker, slice_id=33eb4fc6-71cf-42c0-9b68-3635a00d2d83)
    Error: Failure to update success state, caused by invoking elasticsearch-api _runRequest resulted in a runtime error: Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:354:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:383:7)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)
        at Slice._markCompleted (/app/source/packages/teraslice/lib/workers/worker/slice.js:88:19)
        at <anonymous>
```

**Comment by peterdemartini** [comment]
It seems like the worker is continuing to receive new slices, but failing to change the status of slice state; which makes it looks like it is stuck, but is still doing work. In this scenario, I believe it would be best to fail loudly and to have the worker shutdown itself and allow the clustering to handle restarting the worker.

**Comment by kstaken** [comment]
This is something that @erik-stephens originally observed back in Nov but at the time I failed to connect the dots on what this meant. It appears that even a transient disruption to ES might cause a worker to hang and once it gets into this state then it stops processing and also doesn't shutdown cleanly when asked.

**Comment by peterdemartini** [comment]
@godber nothing shows up in the logs after this particular error appears, at least until the worker is shutdown?

**Comment by godber** [comment]
We don't have logs for this anymore.  We plan on doing things Monday that will possibly trigger this issue again.  We'll collect more logs at that point.

I've been thinking about ways to reproduce this.  First is the direct route is to set up a two node ES cluster and then force a shard to fail over while a job is running.  This tries to reproduce the issue as we think we saw it and of course there's a timing issue which would be hard to get right.

The second thought I had was if we'd trigger the same error by [closing the state index](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-open-close.html) while a job is writing to it.  I think it's more likely that a DIFFERENT error would be triggered by this though.

**Comment by erik-stephens** [comment]
I think have a way to repro.  In my testing, I was able to get teraslice to become unresponsive while I had the data node disconnected.  When I would reconnect the data node, teraslice would become responsive again.  I didn't get the same "fail to update state" error, though.  Either way, I think this could be a good way to test these kinds of scenarios.

To simulate a network partition & heal:
```
docker network disconnect chaos_transport chaos_bar_1

docker network connect chaos_transport chaos_bar_1 --ip 10.10.1.102
```

My setup on a mac:
```
yarn run teraslice --version
yarn run v1.9.4
$ /Users/estephens/src/terascope/teraslice/node_modules/.bin/teraslice --version
0.46.0

docker --version
Docker version 18.06.1-ce, build e68fc7a

docker-compose --version
docker-compose version 1.22.0, build f46880f
```

The docker-compose.yml that I used:
```
---
version: '3'

networks:
  http:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
  transport:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24

services:

  foo:
    image: elastic/elasticsearch:5.6.14
    networks:
      http:
        ipv4_address: 10.10.0.101
      transport:
        ipv4_address: 10.10.1.101
        aliases:
          - master
    environment:
      node.name: foo
      node.master: 'true'
      node.data: 'false'
      transport.host: 10.10.1.101
      cluster.name: chaos
      xpack.security.enabled: 'false'
      xpack.ml.enabled: 'false'
      xpack.watcher.enabled: 'false'
      discovery.zen.ping.unicast.hosts: master
      discovery.zen.minimum_master_nodes: 1
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - '9201:9200'
    expose:
      - '9200/tcp'

  bar:
    image: elastic/elasticsearch:5.6.14
    networks:
      transport:
        ipv4_address: 10.10.1.102
    environment:
      node.name: bar
      node.master: 'false'
      node.data: 'true'
      transport.host: 10.10.1.102
      cluster.name: chaos
      xpack.security.enabled: 'false'
      xpack.ml.enabled: 'false'
      xpack.watcher.enabled: 'false'
      discovery.zen.ping.unicast.hosts: master
      discovery.zen.minimum_master_nodes: 1
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
```
